import type { Dossier } from "./report";

/** Render a dossier as a portable Markdown document (client-side export). */
export function dossierToMarkdown(question: string, dossier: Dossier, vaultText?: string): string {
  const lines: string[] = [];
  lines.push("# Obscura Agent — Dossier", "");
  lines.push(`**Question:** ${question}`, "");
  lines.push(dossier.summary, "");

  if (dossier.findings.length) {
    lines.push("## Findings", "");
    for (const f of dossier.findings) {
      const verdict = f.verdict ? `\`${f.verdict}\` ` : "";
      lines.push(`- ${verdict}${f.claim}`);
      if (f.source_urls.length) {
        lines.push(`  - sources: ${f.source_urls.map((u) => `<${u}>`).join(", ")}`);
      }
    }
    lines.push("");
  }

  if (dossier.open_questions.length) {
    lines.push("## Open questions", "");
    for (const q of dossier.open_questions) lines.push(`- ${q}`);
    lines.push("");
  }

  if (vaultText) {
    lines.push("## Vault brief (E2EE)", "", vaultText, "");
  }

  lines.push("---", "Generated by Obscura Agent · Powered by Venice");
  return lines.join("\n");
}
